export const step = (state) => state.step
export const token = (state) => state.token
export const sessions = (state) => state.sessions
export const orderFilter = (state) => state.orderFilter
export const language = (state) => state.language
export const basic = (state) => state.basic
export const qrcode = (state) => state.qrcode
export const common = (state) => state.common
export const appDownload = (state) => state.appDownload
export const verify = (state) => state.verify
export const authlist = (state) => state.authlist